package com.eternal_plasma.mcmetagen;
//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import java.io.IOException;

public class gui extends JPanel {
    private JButton go;
    private JTextField id;
    private JLabel label1;
    private JLabel label2;
    private JTextField ft;
    private JCheckBox st;

    public gui() {
        //construct components
        go = new JButton("Generate");
        id = new JTextField(5);
        label1 = new JLabel("Block Id you want to animate");
        label2 = new JLabel("Frame Time");
        ft = new JTextField(5);
        st = new JCheckBox("Smooth Transition");

        //adjust size and set layout
        setPreferredSize(new Dimension(432, 320));
        setLayout(null);

        //add components
        add(go);
        add(id);
        add(label1);
        add(label2);
        add(ft);
        add(st);

        //set component bounds (only needed by Absolute Positioning)
        go.setBounds(285, 290, 140, 20);
        id.setBounds(155, 40, 100, 25);
        label1.setBounds(120, 10, 185, 25);
        label2.setBounds(165, 65, 100, 25);
        ft.setBounds(155, 90, 100, 25);
        st.setBounds(145, 125, 135, 20);


        //Logic
        go.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent ae)
            {
                String ID = id.getText();
                String FT = ft.getText();
                String fe = (ID+".png.mcmeta");
                if (st.isSelected()) {
                    System.out.println("Smooth");
                    try {
                        FileWriter myWriter = new FileWriter(fe);
                        myWriter.write("{animation:{interpolate: true,frametime: "+FT+"}}");
                        myWriter.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
                else {
                    System.out.println("Not Smooth");
                    try {
                        FileWriter myWriter = new FileWriter(fe);
                        myWriter.write("{animation:{interpolate: false,frametime: "+FT+"}}");
                        myWriter.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                }
            }
        });


    }


    public static void main (String[] args)
    {


    }
}
